import BottomNav from '@/components/layout/BottomNav';
import type { Metadata } from 'next';
import { ToastContainer } from 'react-toastify';
import './globals.css';
import QueryProvider from './QueryProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <title>ON:SON</title>
      </head>
      <body>
        <div>
          <QueryProvider>
            <ToastContainer />
            <main className="flex-1">{children}</main>
          </QueryProvider>
          <div className="block sm:hidden">
            <BottomNav />
          </div>
        </div>
      </body>
    </html>
  );
}
